------Proyecto: Deteccion de Fraude en Tarjetas de Credito 

PROYECTO: Analisis y Deteccion de Anomalias Financieras
RUBRO: tecnologia financiera / Seguridad Financiera
OBJETIVO: Identificar patrones de riesgo en transacciones anonimizadas.

/*MISIoN DEL PROYECTO:
Transformar datos masivos de transacciones bancarias en informacion estructurada 
y accionable, permitiendo la deteccion temprana de anomalias financieras para 
minimizar el impacto economico del fraude y proteger al usuario final.
*/


